2020-08-06 04:54:45,953 — api.controller — ERROR —predict:81 — Exception on Flask server (predict function): make_prediction() got an unexpected keyword argument 'output_path' 
                 traceback: Traceback (most recent call last):
  File "/home/aikauel/enap/aerialnet_project/packages/ml_api/api/controller.py", line 73, in predict
    response_data = make_prediction(image_bytes.content, imgURL=img_url, generateOutputImg=generateOutputImg, output_path=outputImgPath)
TypeError: make_prediction() got an unexpected keyword argument 'output_path'
Traceback (most recent call last):
  File "/home/aikauel/enap/aerialnet_project/packages/ml_api/api/controller.py", line 73, in predict
    response_data = make_prediction(image_bytes.content, imgURL=img_url, generateOutputImg=generateOutputImg, output_path=outputImgPath)
TypeError: make_prediction() got an unexpected keyword argument 'output_path'
